version: "2"

linters:
  enable:
    - dupl
    - errcheck
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unused

  settings:
    revive:
      rules:
        - name: var-naming
          disabled: true