name: LevelCraft CI

on:
  push

jobs:
  go-services:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Cloning Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26.1"
          cache: true

      - name: Generate go.work
        run: |
          go work init

          for mod in $(find -name go.mod); do
            go work use "$(dirname "$mod")"
          done

      - name: Test go modules
        run: |
          for mod in $(find -name go.mod); do
            dir=$(dirname $mod)
            echo "Testing $dir"
            cd $dir
            go mod download
            go vet ./...
            go test -cover ./...
            go build ./...
            cd -
          done